// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-lYqc-XS15cPXQO1_1RiQ8Blpnz5D7R0',
    appId: '1:260505919168:web:740c9519f28df996be1725',
    messagingSenderId: '260505919168',
    projectId: 'flutterpoc-b3d38',
    authDomain: 'flutterpoc-b3d38.firebaseapp.com',
    storageBucket: 'flutterpoc-b3d38.appspot.com',
    measurementId: 'G-J6QVR2PV77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFKqInf9JFFEJCMoMAJNSBdxNQxxGve2M',
    appId: '1:260505919168:android:8a77959d77fee4e6be1725',
    messagingSenderId: '260505919168',
    projectId: 'flutterpoc-b3d38',
    storageBucket: 'flutterpoc-b3d38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKqH_XQpY-nDBLVCgPCa_n2JoFBuTLq1U',
    appId: '1:260505919168:ios:6803a1b66cb53a1cbe1725',
    messagingSenderId: '260505919168',
    projectId: 'flutterpoc-b3d38',
    storageBucket: 'flutterpoc-b3d38.appspot.com',
    iosClientId: '260505919168-bpfe5v49ontgms4fqpl59ckk68m0baam.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKqH_XQpY-nDBLVCgPCa_n2JoFBuTLq1U',
    appId: '1:260505919168:ios:6803a1b66cb53a1cbe1725',
    messagingSenderId: '260505919168',
    projectId: 'flutterpoc-b3d38',
    storageBucket: 'flutterpoc-b3d38.appspot.com',
    iosClientId: '260505919168-bpfe5v49ontgms4fqpl59ckk68m0baam.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommApp',
  );
}
